itwinjs/core package versions
iTwin/presentation-rules-editor pull request #166
Opened 2024-11-11 14:20 UTC by JonasDov

2024-11-12 06:52 UTC, grigasp commented on app/frontend/src/app/ITwinJsApp/misc/Notifications.ts
> +}
why do you need all of this? can't you take types from itwinui?

2024-11-12 06:52 UTC, grigasp commented on app/frontend/src/app/common/AsyncActionButton.tsx
> +      {/* <Button disabled={actionInProgress} onClick={handleButtonClick}>
needs cleanup?

2024-11-12 06:52 UTC, grigasp commented on presentation-rules-editor-react/package.json
> +    "@itwin/appui-abstract": "^4.9.7",
since we're making a breaking change for itwinui, I think it's okay to make one here too - let's drop version `3` from peer deps, but version `4` should be kept as-is - at `^4.0.0`.

2024-11-12 06:52 UTC, grigasp commented on presentation-rules-editor-react/package.json
>      "@itwin/components-react": "^4.14.1",
dev dependencies should be bumped to latest

2024-11-12 06:52 UTC, grigasp commented on presentation-rules-editor-react/package.json
> +    "@itwin/itwinui-react": "3.15.5"
This is a breaking change, although it doesn't look like one. I think we should make it, though, but additionally please do this:
- specify the version as `"^3.15.5"`,
- make this package a peer dependency,
- don't forget to mention this in changelog.

2024-11-12 08:05 UTC, saskliutas requested changes

2024-11-12 08:05 UTC, saskliutas commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +  const columns = React.useMemo(
By removing `TableProps` we lose a little bit of type checking (and intelisnse) on column object. Are there nor replacement?

2024-11-12 08:05 UTC, saskliutas commented on app/frontend/src/app/ITwinJsApp/misc/Notifications.ts
> +export function displayToast(toaster: Toaster, messageType: OutputMessagePriority, messageShort: string, _messageDetail?: string): void {
Maybe instead of passing `Toaster` to this function we could have custom hook that would not expose `Toaster` like this:
```ts
function useToaster() {
  const toaster = useItwinUIToaster();
  return (messageType: OutputMessagePriority, messageShort: string) => {
    // handle message
  }
}
```

2024-11-12 13:52 UTC, JonasDov commented on app/frontend/src/app/ITwinJsApp/misc/Notifications.ts
> +}
ItwinUI does not export those types, they can be infered from useToaster, but they are no longer necessary with new changes.

2024-11-12 13:53 UTC, JonasDov commented on app/frontend/src/app/common/AsyncActionButton.tsx
> +      {/* <Button disabled={actionInProgress} onClick={handleButtonClick}>
cleaned up

2024-11-12 13:53 UTC, JonasDov commented on presentation-rules-editor-react/package.json
> +    "@itwin/appui-abstract": "^4.9.7",
Changed

2024-11-12 13:53 UTC, JonasDov commented on presentation-rules-editor-react/package.json
>      "@itwin/components-react": "^4.14.1",
Bumped

2024-11-12 13:54 UTC, JonasDov commented on presentation-rules-editor-react/package.json
> +    "@itwin/itwinui-react": "3.15.5"
I specified the version as `^3.0.0` since we are not using anything that was added to newer versions

2024-11-12 13:54 UTC, JonasDov commented on app/frontend/src/app/ITwinJsApp/content-tabs/ContentTabs.tsx
> +  const handleShareButtonClick = React.useCallback(async () => {
It isn't removed

2024-11-12 13:54 UTC, JonasDov commented on app/frontend/src/app/AppHeader.tsx
> +  const actions = React.useMemo(() => {
It isn't removed

2024-11-12 13:56 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +  const columns = React.useMemo(
ItwinUI v3, adds `satisfies` to add type checking (can be seen here: https://itwin.github.io/iTwinUI/react/?source=true&story=table--column-manager#ladle_loc_3024). Changed to use `satisfies`

2024-11-12 13:56 UTC, JonasDov commented on app/frontend/src/app/ITwinJsApp/misc/Notifications.ts
> +export function displayToast(toaster: Toaster, messageType: OutputMessagePriority, messageShort: string, _messageDetail?: string): void {
Added a hook called `useToastMessage` which does what you suggested

2024-11-12 14:04 UTC, saskliutas requested changes

2024-11-12 14:04 UTC, saskliutas commented on app/frontend/src/app/AppHeader.tsx
> +        <MenuExtraContent key={0}>
I guess we could use more meaningful keys like: "displayName", "divider", "signout".

2024-11-12 14:04 UTC, saskliutas commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +type ITwinBrowserTableData = {
```suggestion
interface ITwinBrowserTableData {
```

2024-11-12 14:04 UTC, saskliutas commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +type IModelBrowserTableData = {
```suggestion
interface IModelBrowserTableData {
```

2024-11-12 14:04 UTC, saskliutas commented on app/frontend/src/app/IModelBrowser/LocalIModelBrowser.tsx
> +type TableData = {
```suggestion
interface TableData {
```

2024-11-12 14:04 UTC, saskliutas commented on presentation-rules-editor-react/package.json
> +    "@itwin/itwinui-react": "^3.0.0",
`@itwin/itwinui-react` should be added to dev dependencies after if was moved from direct to peer dependencies.

2024-11-12 14:15 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/LocalIModelBrowser.tsx
> +type TableData = {
If i change it to interface i get the following:
![image](https://github.com/user-attachments/assets/20c9f490-9172-40b8-9781-ee484c786cc8)

2024-11-12 14:15 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +type ITwinBrowserTableData = {
If i change it to interface i get the following:
![image](https://github.com/user-attachments/assets/20c9f490-9172-40b8-9781-ee484c786cc8)

2024-11-12 14:21 UTC, JonasDov commented on presentation-rules-editor-react/package.json
> +    "@itwin/itwinui-react": "^3.0.0",
Added to dev dependencies

2024-11-12 14:21 UTC, saskliutas commented on app/e2e-tests/src/header.test.ts
> +    const header = page.locator(".page-header nav");
I think the last usage of `locator` could be replaced with `page.getByRole("navigation")`

2024-11-12 14:21 UTC, JonasDov commented on app/frontend/src/app/AppHeader.tsx
> +        <MenuExtraContent key={0}>
Changed

2024-11-12 14:58 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +type ITwinBrowserTableData = {
Changed to use `Record<"prop1" | "prop2" |..., string>`, this allows to remove `// eslint-disable-next-line @typescript-eslint/consistent-type-definitions`

2024-11-12 14:58 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/ITwinIModelBrowser.tsx
> +type IModelBrowserTableData = {
Changed to use `Record<"prop1" | "prop2" |..., string>`, this allows to remove `// eslint-disable-next-line @typescript-eslint/consistent-type-definitions`

2024-11-12 14:58 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/LocalIModelBrowser.tsx
> +type TableData = {
Changed to use `Record<"prop1" | "prop2" |..., string>`, this allows to remove `// eslint-disable-next-line @typescript-eslint/consistent-type-definitions`

2024-11-12 16:06 UTC, saskliutas commented on app/frontend/package.json
> +    "react": "^18.3.1",
I guess `@types/react`, `@types/react-dom`, `@types/node` should be bumped also.

2024-11-14 13:52 UTC, JonasDov commented on app/frontend/package.json
> +    "react": "^18.3.1",
Bumped all versions

2024-11-14 13:52 UTC, JonasDov commented on app/frontend/src/app/ITwinJsApp/ui-framework/UIFramework.tsx
> +    <Provider
No, removed

2024-11-14 14:01 UTC, grigasp requested changes

2024-11-14 15:22 UTC, JonasDov commented on app/frontend/src/app/IModelBrowser/IModelBrowser.tsx
> +                        label="Open grid view"
It requires some work, it's not as simple as just adding it to the `label` property, since IModelApp is not always initialized. I think this should be done in a separate PR. Added an issue: https://github.com/iTwin/presentation-rules-editor/issues/167

2024-11-15 08:04 UTC, saskliutas approved these changes

2024-11-15 08:24 UTC, grigasp approved these changes

2024-11-15 08:24 UTC, merged

2024-11-15 08:24 UTC, grigasp requested changes
Forgot to ask to update the [changelog](https://github.com/iTwin/presentation-rules-editor/blob/master/presentation-rules-editor-react/CHANGELOG.md). Please do that in a separate PR.