Add ability to open demo iModels without signing in
iTwin/presentation-rules-editor pull request #69
Opened 2022-03-16 10:27 UTC by roluk

The list of permitted demo iModels is hardcoded and is the same that's available in iTwin.js sandboxes.

2022-03-16 12:33 UTC, grigasp requested changes

2022-03-16 12:33 UTC, grigasp commented on app/frontend/src/app/ITwinJsApp/IModelIdentifier.tsx
> +const demoIModelsIndex = new Map([...demoIModels.values()].map(({ iTwinId, iModelId }) => [iTwinId, iModelId]));
Having a map where the key is iTwinId and value is iModelId is really confusing, especially the `demoIModelsIndex.get(identifier.iTwinId) === identifier.iModelId` check in `isDemoIModel` function. In theory an iTwin can contain multiple iModels, so associating them like that is not really correct.

I think we can just keep a plain set of iModelIds here, since they're already globally unique.

2022-03-16 14:26 UTC, roluk commented on app/frontend/src/app/ITwinJsApp/IModelIdentifier.tsx
> +const demoIModelsIndex = new Map([...demoIModels.values()].map(({ iTwinId, iModelId }) => [iTwinId, iModelId]));
There is no UI for it yet, but the intention behind the map object is to have a canonical list of available demo iModels which user can select to view. To avoid keeping this and a separate list of iModel ids manually in sync, I chose to generate one list out of another.

2022-03-17 05:54 UTC, grigasp commented on app/frontend/src/app/ITwinJsApp/IModelIdentifier.tsx
> +const demoIModelsIndex = new Map([...demoIModels.values()].map(({ iTwinId, iModelId }) => [iTwinId, iModelId]));
> To avoid keeping this and a separate list of iModel ids manually in sync, I chose to generate one list out of another.

That's fine. I just think that you can generate a `Set` instead of a `Map`:
```ts
const demoIModelsIndex = new Set([...demoIModels.values()].map(({ iModelId }) => iModelId));
```

2022-03-17 11:51 UTC, roluk commented on app/frontend/src/app/ITwinJsApp/IModelIdentifier.tsx
> +const demoIModelsIndex = new Map([...demoIModels.values()].map(({ iTwinId, iModelId }) => [iTwinId, iModelId]));
I don't think it's a good idea to accept `IModelIdentifier` that specifies an existing demo iModel but incorrect iTwinId. We use iModel and iTwin identifiers in `CheckpointConnection.openRemote` call, so both must be correct.

If iTwinId wasn't specified in the URL, we could call an iTwin API to find it from iModelId, but that would incur an additional server roundtrip before an iModel can be opened, so I think requiring both ids is the best option.

2022-03-18 08:31 UTC, grigasp commented on app/frontend/src/app/ITwinJsApp/IModelIdentifier.tsx
> +const demoIModelsIndex = new Map([...demoIModels.values()].map(({ iTwinId, iModelId }) => [iTwinId, iModelId]));
I think I heard someone talking about not requiring an iTwinId when opening an iModel, but I'm not sure if or when that would be happening. I don't think the additional iTwinId check is necessary, but I don't mind you keeping it if you want.

2022-03-18 08:31 UTC, grigasp approved these changes

2022-03-18 13:36 UTC, merged